/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/bird.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Bird(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('models/bird.glb')
  const { actions } = useAnimations(animations, group)
  // console.log(actions)
  useEffect(() => {
    for (const action of Object.values(actions)) {
      action.play()
    }
    // actions['Bird.001Action'].play()
  }, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Bird" position={[0.468, 2.379, 1.512]} rotation={[0.051, 0.029, 0.03]}>
          <mesh name="lwing" geometry={nodes.lwing.geometry} material={materials.Material} position={[1.159, 0, 0]} />
          <mesh name="rwing" geometry={nodes.rwing.geometry} material={materials.Material} position={[-1.354, 0, 0]} />
          <mesh name="body" geometry={nodes.body.geometry} material={materials.Material} position={[-0.094, -0.001, -1.684]} scale={5.881} />
        </group>
        <group name="Bird001" position={[-8.749, 0.152, -15.788]} rotation={[0, 0.233, 0]}>
          <mesh name="lwing001" geometry={nodes.lwing001.geometry} material={materials.Material} position={[1.159, 0, 0]} />
          <mesh name="rwing001" geometry={nodes.rwing001.geometry} material={materials.Material} position={[-1.354, 0, 0]} />
          <mesh name="body001" geometry={nodes.body001.geometry} material={materials.Material} position={[-0.094, -0.001, -1.684]} scale={5.881} />
        </group>
        <group name="Bird002" position={[17.395, 1.493, -16.163]}>
          <mesh name="lwing002" geometry={nodes.lwing002.geometry} material={materials.Material} position={[1.159, 0, 0]} />
          <mesh name="rwing002" geometry={nodes.rwing002.geometry} material={materials.Material} position={[-1.354, 0, 0]} />
          <mesh name="body002" geometry={nodes.body002.geometry} material={materials.Material} position={[-0.094, -0.001, -1.684]} scale={5.881} />
        </group>
        <group name="Bird003" position={[8.9, -3.36, -31.724]} rotation={[0.055, -0.101, 0.03]}>
          <mesh name="lwing003" geometry={nodes.lwing003.geometry} material={materials.Material} position={[1.159, 0, 0]} />
          <mesh name="rwing003" geometry={nodes.rwing003.geometry} material={materials.Material} position={[-1.354, 0, 0]} />
          <mesh name="body003" geometry={nodes.body003.geometry} material={materials.Material} position={[-0.094, -0.001, -1.684]} scale={5.881} />
        </group>
        <group name="Bird004" position={[-14.92, -3.063, -38.51]} rotation={[0.051, 0.029, 0.03]}>
          <mesh name="lwing004" geometry={nodes.lwing004.geometry} material={materials.Material} position={[1.159, 0, 0]} />
          <mesh name="rwing004" geometry={nodes.rwing004.geometry} material={materials.Material} position={[-1.354, 0, 0]} />
          <mesh name="body004" geometry={nodes.body004.geometry} material={materials.Material} position={[-0.094, -0.001, -1.684]} scale={5.881} />
        </group>
        <group name="Bird005" position={[28.456, 3.3, -34.134]}>
          <mesh name="lwing005" geometry={nodes.lwing005.geometry} material={materials.Material} position={[1.159, 0, 0]} />
          <mesh name="rwing005" geometry={nodes.rwing005.geometry} material={materials.Material} position={[-1.354, 0, 0]} />
          <mesh name="body005" geometry={nodes.body005.geometry} material={materials.Material} position={[-0.094, -0.001, -1.684]} scale={5.881} />
        </group>
        <group name="Bird006" position={[88.985, -12.447, -63.488]} rotation={[0.051, 0.029, 0.03]}>
          <mesh name="lwing006" geometry={nodes.lwing006.geometry} material={materials.Material} position={[1.159, 0, 0]} />
          <mesh name="rwing006" geometry={nodes.rwing006.geometry} material={materials.Material} position={[-1.354, 0, 0]} />
          <mesh name="body006" geometry={nodes.body006.geometry} material={materials.Material} position={[-0.094, -0.001, -1.684]} scale={5.881} />
        </group>
        <group name="Bird007" position={[55.362, -2.757, -49.718]} rotation={[0.051, 0.029, 0.03]}>
          <mesh name="lwing007" geometry={nodes.lwing007.geometry} material={materials.Material} position={[1.159, 0, 0]} />
          <mesh name="rwing007" geometry={nodes.rwing007.geometry} material={materials.Material} position={[-1.354, 0, 0]} />
          <mesh name="body007" geometry={nodes.body007.geometry} material={materials.Material} position={[-0.094, -0.001, -1.684]} scale={5.881} />
        </group>
        <group name="Bird008" position={[-31.649, 1.51, -30.992]} rotation={[0.045, 0.216, 0.031]}>
          <mesh name="lwing008" geometry={nodes.lwing008.geometry} material={materials.Material} position={[1.159, 0, 0]} />
          <mesh name="rwing008" geometry={nodes.rwing008.geometry} material={materials.Material} position={[-1.354, 0, 0]} />
          <mesh name="body008" geometry={nodes.body008.geometry} material={materials.Material} position={[-0.094, -0.001, -1.684]} scale={5.881} />
        </group>
        <group name="Bird009" position={[-30.249, 0.652, -83.305]} rotation={[0.051, 0.029, 0.03]}>
          <mesh name="lwing009" geometry={nodes.lwing009.geometry} material={materials.Material} position={[1.159, 0, 0]} />
          <mesh name="rwing009" geometry={nodes.rwing009.geometry} material={materials.Material} position={[-1.354, 0, 0]} />
          <mesh name="body009" geometry={nodes.body009.geometry} material={materials.Material} position={[-0.094, -0.001, -1.684]} scale={5.881} />
        </group>
        <group name="Bird010" position={[-53.895, 3.667, -63.396]}>
          <mesh name="lwing010" geometry={nodes.lwing010.geometry} material={materials.Material} position={[1.159, 0, 0]} />
          <mesh name="rwing010" geometry={nodes.rwing010.geometry} material={materials.Material} position={[-1.354, 0, 0]} />
          <mesh name="body010" geometry={nodes.body010.geometry} material={materials.Material} position={[-0.094, -0.001, -1.684]} scale={5.881} />
        </group>
        <group name="Bird011" position={[56.685, 7.473, -78.817]} rotation={[0, -0.168, 0]}>
          <mesh name="lwing011" geometry={nodes.lwing011.geometry} material={materials.Material} position={[1.159, 0, 0]} />
          <mesh name="rwing011" geometry={nodes.rwing011.geometry} material={materials.Material} position={[-1.354, 0, 0]} />
          <mesh name="body011" geometry={nodes.body011.geometry} material={materials.Material} position={[-0.094, -0.001, -1.684]} scale={5.881} />
        </group>
        <group name="Bird012" position={[115.378, -10.436, -115.378]} rotation={[-0.016, -0.036, -0.014]}>
          <mesh name="lwing012" geometry={nodes.lwing012.geometry} material={materials.Material} position={[1.159, 0, 0]} />
          <mesh name="rwing012" geometry={nodes.rwing012.geometry} material={materials.Material} position={[-1.354, 0, 0]} />
          <mesh name="body012" geometry={nodes.body012.geometry} material={materials.Material} position={[-0.094, -0.001, -1.684]} scale={5.881} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/bird.glb')
